name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        env:
            MYSQL_ROOT_PASSWORD: secret
        strategy:
            matrix:
                node-version: ['16.x']
        steps:
            - uses: actions/checkout@v2
            - name: Shutdown Ubuntu MySQL (SUDO)
              run: sudo service mysql stop
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Set up MySQL 5.7
              uses: mirromutth/mysql-action@master
              with:
                  mysql database: 'share-a-meal' # Optional, default value is "test". The specified database which will be create
                  mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
                  mysql user: 's-a-m-user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
                  mysql password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"                  mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            - name: npm install and test
              run: |
                  npm install
                  npm test -- --password=${{ secrets.MYSQL_ROOT_PASSWORD }}
              env:
                  CI: true

    deploy:
        needs: integrationtests
        runs-on: ubuntu-latest
        environment:
            name: Heroku # naam van mijn environment op GitHub
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: shareameal-prog4
                  heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
