name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        env:
            MYSQL_ROOT_PASSWORD: verysecret
            DB_HOST: localhost
            DB_PORT: 3306
            DB_DATABASE: s_a_m
            DB_USER: sam_user
            DB_PASSWORD: geheim
        strategy:
            matrix:
                node-version: ['14.x', '16.x']
        steps:
            - uses: actions/checkout@v2

            - name: Shutdown Ubuntu MySQL (SUDO)
              run: sudo service mysql stop

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set up MySQL 5.7
              # https://github.com/mirromutth/mysql-action/blob/master/README.md
              uses: mirromutth/mysql-action@master
              with:
                  mysql database: ${{env.DB_NAME}} # Optional, default value is "test". The specified database which will be create
                  mysql root password: ${{env.MYSQL_ROOT_PASSWORD}} # Required if "mysql user" is empty, default is empty. The root superuser password
                  mysql user: ${{env.DB_USER}} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
                  mysql password: ${{env.DB_PASSWORD}} # Required if "mysql user" exists. The password for the "mysql user"                  mysql root password: ${{MYSQL_ROOT_PASSWORD}}

            - name: npm install
              run: |
                  npm install

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $DB_PASSWORD --DB_USER $DB_USER --DB_NAME $DB_NAME

    deploy:
        needs: integrationtests
        runs-on: ubuntu-latest
        environment:
            name: Heroku # naam van mijn environment op GitHub
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: shareameal-prog4
                  heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
