name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        env:
            MYSQL_ROOT_PASSWORD: secret
            DB_HOST: localhost
            DB_PORT: 3306
            DB_DATABASE: share-a-meal
            DB_USER: sam_user
            DB_PASSWORD: secret
        services:
            mysql:
                image: mysql:5.7
                # # env:
                # #     MYSQL_ROOT_PASSWORD: password
                # # ports:
                # #     - 32574:3306
                # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v2
            - name: Verify MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  #   mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
                  mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -uroot -p${{ env.MYSQL_ROOT_PASSWORD }}
                  # mysql -h ${{env.DB_HOST}} --port 3306 -uroot -p${{env.MYSQL_ROOT_PASSWORD}} -e "CREATE DATABASE share-a-meal;"
                  mysql -h ${{env.DB_HOST}} --port 3306 -uroot -p${{env.MYSQL_ROOT_PASSWORD}} < share-a-meal.create.sql
                  mysql -h ${{env.DB_HOST}} --port 3306 -uroot -p${{env.MYSQL_ROOT_PASSWORD}} share-a-meal -e "SHOW TABLES;"

            - name: npm install
              run: |
                  npm install

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_NAME

    deploy:
        needs: integrationtests
        runs-on: ubuntu-latest
        environment:
            name: Heroku # naam van mijn environment op GitHub
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: shareameal-prog4
                  heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
